services:
  postgres:
    image: postgres:17
    container_name: hrbank-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - hrbank-postgres-data:/var/lib/postgresql/data

volumes:
  hrbank-postgres-data: